### ISSUE TITLE
Examples should be as apps devs will use the library

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#2456]
Back in https://github.com/openlayers/ol3/issues/241#issue-11583741 @elemoine wrote "the examples should clearly show how we expect people to use OpenLayers 3". Although Plovr has now been removed, this is still not the case. I am starting to write a 'find your way round the api' tutorial, and was planning on basing this on the examples, but the problem is there are so many 'remove this' and 'change that' that I'm thinking this is more trouble than it's worth. If a tutorial like this cannot use the examples as they stand, I'm questioning their value - despite Plovr removal, they continue to make OL3 appear harder to use than it is.

1. is rendererFromQueryString really needed? How many people regularly use this? Most apps developers are probably unaware you can load different renderers in the hosted examples, and I find it hard to think of a case in production code where you would change the renderer (or indeed need >1 in your build).
2. the `goog.require`s are only needed if you compile code with the library or want 'raw', which most people won't do. In the same comment, Eric also says "I don't think that we need to compile the examples' code together with the lib", but even if we do the requires could be stored in separate files passed to the compiler.
3. are the typecasts needed? If the code without typecasts produces compiler errors, would it not be better to change the config so these produce warnings not errors? I've just been looking at a question on [stackoverflow](http://stackoverflow.com/questions/24774180/fixed-size-of-an-icon-openlayers3/24776908#24776908) which shows that people have the wrong impression that apps code needs this stuff.
4. is the special loader needed? Can this not be handled by the framework on the server rather than put in every html in the repo? As with the renderers, most developers are probably unaware you can load different builds.
5. also, would the bootstrap stuff not be better handled by the framework on the server rather than repeated in every html?

**Comment by bartvde** [comment]
This has been addressed by the recent example template work by mainly @ahocevar

**Comment by probins** [comment]
not really. I think the templating was a good improvement, but the issues are still there. If I use the online examples and open page source, I see reference, for example, to a loader script. If I click on the 'show source' link, I see exampleNS.getRendererFromQueryString. If I look at the source in examples_src, I see lots of goog.requires. It's not going to be clear to any newbie what these are, whether they have to be used, why, etc.

In fact, in one way, it's worse. I wrote a examples/readme to explain the differences. This has now moved to config/examples. A newbie is not going to know to look there, so IMO it would be better if this text was moved back to examples_src; or perhaps better would be a link from the online examples.

**Comment by bartvde** [comment]
did you check the online examples on master?

**Comment by bartvde** [comment]
i.e. the ones that have the full example code which can be copied to clipboard and to jsfiddle so code that doesn't use the loader at all

**Comment by probins** [comment]
ah right, apologies. No, I was dumbly just clicking on the examples link from the home page, and not noticing this loads 3.4 not master. Yes, that really does seem to fix the issues. Very impressive piece of work :-)

My only comment would be that perhaps it would be good for examples_src/readme to point to the online examples: 'Go to ... to see these examples as they might be used in a production environment' or something like that.
