### ISSUE TITLE
ImageWMS infinite loop bug

### ISSUE THREAD

**Issue by ebradshaw** [openlayers/ol3#3334]
I've been struggling with an issue where an ImageWMS layer will occasionally get stuck in the "loading" imageState, regardless of the fact that the actual image load has completed.  Once this has happened, a render loop continuously fires until the viewport is changed and the layer redrawn.  I've tried several things to detect and work around this issue, but none of them have worked.  Has anyone else ran into this problem?  It's occuring in Chrome for me, haven't tested other browsers.

**Comment by ahocevar** [comment]
Can this be reproduced with one of the official examples? Or can you provide a jsfiddle that shows the issue? Thanks!

**Comment by xingfuryda** [comment]
This is tricky to reproduce, but I am experiencing the same problem. I can reproduce on my local machine by browsing to a local web and WMS server, as well as browsing to a site served from a remote server. I've put together a jsfiddle and I only seem to notice the problem when viewing the page 'embedded' so that the map fills most of the browser window.

To reproduce I need to perform a small pan a number of times. I might need to perform the pan 4 or 5 times before I can notice the bug.

Although an image is sent from the WMS to the browser (as seen in Chrome Dev Tools network tab), it seems OL won't load the image and gets caught in an infinite loop. If I then pan or zoom again then the next image is rendered fine. As a start, I would place a breakpoint here and find it would be called repeatedly until I pan or zoom:

ol.source.Image.prototype.handleImageChange = function(event)

Windows 7 64-bit, Chrome 43.0.2357.124, ol-debug.js v3.6.0-16-g4aa3ef5

http://jsfiddle.net/0wwm8tmy/

http://jsfiddle.net/0wwm8tmy/embedded/result/

**Comment by ahocevar** [comment]
Should be fixed with #3933. @xingfuryda or @ebradshaw, can you please verify?

**Comment by xingfuryda** [comment]
Not fixed I'm afraid. I've updated the fiddle (only changing the WMS layer list so the fiddle still works) http://jsfiddle.net/ufm2uv7t/embedded/result/

Image is downloaded to the browser from the WMS fine, but not rendered by OL.

fiddle is using:
v3.8.0-12-g575fff6
http://openlayers.org/en/master/build/ol-debug.js

**Comment by ahocevar** [comment]
@xingfuryda The fiddle you linked above works fine for me in all browsers.

**Comment by xingfuryda** [comment]
Ok @ahocevar thanks for testing. Would a screen recorded video assist or do you have another suggestion on how to communicate around this issue?

**Comment by ahocevar** [comment]
#3964 will also fix the issue, if it isn't fixed already. So things should really be working soon.

**Comment by rattai** [comment]
FYI, I'm seeing the bug in @xingfuryda's jsfiddle.  You have to pan and zoom around a lot.  The bug depends on the map extent....so you have to find one that triggers the bug.

Wait for the layer to re-render after each pan or zoom.  After a render fails, set a breakpoint at line 111490 of ol-debug.js.

You'll see this called over and over again in an infinite loop because the `containsExtent()` check (line 111494) fails every time.  This causes the LOADED image to be replaced by a brand new one...starting the loop over again.

Anyway, #3964 is my attempt to fix this.

**Comment by xingfuryda** [comment]
Verified in Version: v3.8.2-38-gdaf85c7, thanks!
