### ISSUE TITLE
Linestring unexpected behaviour

### ISSUE THREAD

**Issue by jonataswalker** [openlayers/ol3#3701]
Hello all,

I'm trying to simulate a cluster. I got 2 (or more) markers on same coordinate and on mouseover I show them a little bit separated, joined by linestrings.

[Live Demo] (http://plnkr.co/edit/CuDYJe?p=preview)

So, steps to reproduce:
* Mouseover on marker
* zoom in and zoom out
  * several times

Unexpected
![workspace 1_011](https://cloud.githubusercontent.com/assets/10571881/7682222/e9f9894e-fd4c-11e4-9dd9-978f450ac0aa.png)

Expected
![workspace 1_012](https://cloud.githubusercontent.com/assets/10571881/7682228/f586a986-fd4c-11e4-8933-e031eaa554ec.png)

Thanks for your work.

**Comment by alvinlindstam** [comment]
I can't reproduce. It seems like your plunker link is different from your screenshots, since it looks different, don't expand on mouseover (but on clicks) and only expands to one direction.
![skarmavbild 2015-05-18 kl 16 14 59](https://cloud.githubusercontent.com/assets/1712882/7682544/1268bf5e-fd79-11e4-9982-de5982460c37.png)

**Comment by jonataswalker** [comment]
You're right. Fixed now. Same link, plz.

**Comment by alvinlindstam** [comment]
You forgot to remove/clear the old linestrings in the multiLineString geometry, so the old lines were always kept even when zoom changed.

Try adding multiLineString.setCoordinates([]) to line 205: http://plnkr.co/edit/uA75itjtIISpwKiVc0C4?p=preview

**Comment by jonataswalker** [comment]
@alvinlindstam, you're right again. Solved.

Thank you man.
