### ISSUE TITLE
JSFiddle examples broken

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#5250]
If you go to [one of the hosted examples](http://openlayers.org/en/v3.15.1/examples/simple.html) and click "edit" you get taken to JSFiddle but the example doesn't work.

In the console are two errors related to http://jsfiddle.net/css//css/light.css?update_19_04_2016_1 not being found.  And one uncaught `ReferenceError: ol is not defined`.

**Comment by probins** [comment]
if you click 'run', though, it still works

**Comment by jonataswalker** [comment]
At least for me this is caused by Mixed Content - HTTP (OL files) resources load over HTTPS.

**Comment by fredj** [comment]
fixed with  #5976

**Comment by tschaub** [comment]
It looks examples still don't run on load.  For example, open https://openlayers.org/en/v3.15.1/examples/simple.html and click the "Edit" button.

Curious if this is the way it has to be.

**Comment by jonataswalker** [comment]
> if you click 'run', though, it still works

Now this is valid.
