### ISSUE TITLE
MapBrowserPointerEvent not in api docs

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#5414]
For example, http://openlayers.org/en/master/apidoc/ol.interaction.ModifyEvent.html points to http://openlayers.org/en/master/apidoc/ol.MapBrowserPointerEvent.html, but this page does not exist.

Am I right in thinking that `oli.MapBrowserPointerEvent` needs to be added to `externs/oli.js` and that `ol.MapBrowserPointerEvent` needs to implement it?

**Comment by ahocevar** [comment]
> Am I right in thinking that oli.MapBrowserPointerEvent needs to be added to externs/oli.js and that ol.MapBrowserPointerEvent needs to implement it?

Yes, that should fix the problem.

**Comment by probins** [comment]
ok, PR coming up

**Comment by probins** [comment]
no, this doesn't fix the problem. I also added an `@classdesc` and that doesn't fix the problem either. Is it because `ol.MapBrowserPointerEvent` doesn't export anything, other than what it inherits from `ol.MapBrowserEvent`, so does it need an `@inheritDoc` - if so, where?

**Comment by tschaub** [comment]
Not directly related to what you're trying to do, but this should really be called `ol.PointerEvent`.  The `MapBrowser` part is so weird.

**Comment by probins** [comment]
and should there be `@fires` for those objects which fire this event?

**Comment by probins** [comment]
https://github.com/openlayers/ol3/compare/master...probins:mbpe is what I've changed.

**Comment by ahocevar** [comment]
@probins I'll try to find some time to look into this later today.

**Comment by probins** [comment]
> this should really be called ol.PointerEvent

we already have `ol.pointer.PointerEvent`. Personally, I've always preferred the suggestion way back in #2334

**Comment by probins** [comment]
@ahocevar did you find some time to look into this?

**Comment by ahocevar** [comment]
Not yet unfortunately @probins. But I still have the ticket open in an extra tab in my browser, so it's on my radar.

**Comment by ahocevar** [comment]
Ok, `ol.MapBrowserPointerEvent` does not export anything beyond what `ol.MapBrowserEvent` expiorts, so I think it makes sense to remove this property in favour of the underlying `ol.MapBrowserEvent`. See #5414.
