### ISSUE TITLE
Polygon LineDash performance problems

### ISSUE THREAD

**Issue by LudvikAdamec** [openlayers/ol3#5520]
There is big performance problem in higher zoom level for polygon layers only in case of using lineDash stroke and it is almost impossible to pan a map. In lower zoom level is performance ok. I made jsfiddle:  http://jsfiddle.net/gbg4a2kf/4/

**Comment by ahocevar** [comment]
The performance problem should go away with shorter line segments, because OpenLayers will optimize the geometries it has to render to only include the visible segments.

**Comment by jeroenvheel** [comment]
Is openlayers missen a beginPath() call
See this issue-> http://stackoverflow.com/questions/17001112/slow-performance-drawing-dashed-lines-in-html5-canvas

**Comment by ahocevar** [comment]
Where exactly are we missing a beginPath instruction?

**Comment by jeroenvheel** [comment]
with the new release 3.18.0 and overlap on true on a ol.source.Vector the poor performance went away

**Comment by ahocevar** [comment]
`overlaps: true` is the default. You benefit from another performance improvement here: #5708.

**Comment by ahocevar** [comment]
Fixed with #5708.

**Comment by JackD83** [comment]
This is still a problem for me.

Try this example: https://codepen.io/anon/pen/LLeaJg?editors=1010

Draw a line acrosse the US and then zoom in on it. On higher zoom levels everything becomes very slow and unresponsive. If you zoom in further, the line becomes solid and everything is fine again.  My workarround is currently the same as the one  used in OL to disable the lineDash if the user zooms in. I can not add more line segments as I dont know what the user is drawing and at which zoom level
