### ISSUE TITLE
Selecting on mobile devices is almost impossible

### ISSUE THREAD

**Issue by giohappy** [openlayers/ol3#5862]
Selecting points and lines with touch is a metter of luck. It becomes more reliable from 10px up, but 10px wide lines (and points) are generally too big.
It's related to #2105.
Anybody willing to work on this? We could fund it (at least partially).

**Comment by giohappy** [comment]
Probably the solution implemented in ol.interaction.Modify could be ported to selection too.

**Comment by cvenzin** [comment]
You can implement something by your self on top of the ol3 api. I've chosen an algorithm from here [Looping in a spiral](http://stackoverflow.com/questions/398299/looping-in-a-spiral), with the idea to call forEachFeatureAtPixel on all neighboring pixels in a limited range. After the first feature is hit the algorithm stops and I progress in my workflow. 
I've also seen other solutions using getClosestFeatureToCoordinate on the vector layers. Not sure which way is more performant. I'm fine with my solution.
```
map.on('click', (evt) => {
                this.calcHitMatrix(evt.pixel);
        });
private calcHitMatrix(pixel: number[]) {
        let X = 11; // -5 to + 5 in x
        let Y = 11; // -5 to + 5 in y
        let x = 0;
        let y = 0;
        let dx = 0;
        let dy = -1;
        let t = Math.max(X, Y);
        let maxI = t * t;
        let pixelX = pixel[0];
        let pixelY = pixel[1];
        for (let i = 0; i < maxI; i++) {
            if ((-X / 2 <= x) && (x <= X / 2) && (-Y / 2 <= y) && (y <= Y / 2)) {
                if (this.displayFeatureInfo([pixelX + x, pixelY + y])) {
                    return;
                }
            }
            if ((x === y) || ((x < 0) && (x === -y)) || ((x > 0) && (x === 1 - y))) {
                t = dx;
                dx = -dy;
                dy = t;
            }
            x += dx;
            y += dy;
        }
    }

private displayFeatureInfo(pixel) {
        return this.mapService.map.forEachFeatureAtPixel(pixel, (feature, layer) => {
            return this.cbForEachFeatureAtPixel(feature, layer, pixel);
        });
    }

private cbForEachFeatureAtPixel(feature: any, layer: any, pixel: number[]) {
        if (layer && layer.get('hxgnReport')) {
            this.mapService.overlayLayer.getSource().addFeature(feature);
            let report = layer.get('hxgnReport');
            console.log("feature hit with reportId " + report.id + ", propertyName " + report.propertyName + " and propertyValue " + feature.get(report.propertyName));
            let popover = this.popoverCtrl.create(ReportComponent, {
                report: report,
                feature: feature,
                layer: layer,
                navController: this.navController
            });

            // create a fake event for ionic
            let ionicEvent = {
                target: {
                    getBoundingClientRect: () => {
                        return {
                            top: pixel[1],
                            left: pixel[0]
                        };
                    }
                }
            };
            popover.present({
                ev: ionicEvent
            });
            return true;
        } else {
            return false;
        }
    }
```

**Comment by ischas** [comment]
In general the company I work for is interested in this issue as well. @simonseyock and I discussed yesterday how to solve it inside of the library. We thought about a buffer parameter for ol.Map#forEachFeatureAtPixel which ends either in a solution similar to what @cvenzin inside of the ol.Map#forEachFeatureAtPixel method or which may lead to changes in many parts of the software since ol.Map#forEachFeatureAtPixel uses ol.renderer.*#forEachFeatureAtCoordinate and this is implemented at several places.

@giohappy If you're not satisfied with the solution given above you may contact me (see my email in my profile page) and we can discuss how to bundle our forces to solve this issue.

**Comment by giohappy** [comment]
thanks @cvenzin for the smart solution. I was also thiniking to something similar but ( @ischas this is also for you) what about implementing the same approach  used by [ol.interaction.Modify.prototype.handlePointerAtPixel](https://github.com/openlayers/ol3/blob/master/src/ol/interaction/modify.js#L684)? There rBush is being used to find the nearest segment (or point) to the hit coordinates. Using the same approach would keep OL3 coherent.

**Comment by ischas** [comment]
You cannot work with an rbush of features since the rbush doesn't know how the features are displayed. You may have styled a POI with a huge icon and you want to select the POI not just by clicking on the coordinate (which may be saved in an rbush) but on any pixel of the icon. So the renderer has to be used for hit detection.

**Comment by giohappy** [comment]
Yes @ischas good point. Extending canvas and webgl reaplygroups' forEachFeatureAtCoordinate would be definetely the way to go.

**Comment by tsauerwein** [comment]
The best way to tackle this is to use a higher stroke width for the hit detection rendering. Different replay groups (a collection of canvas draw commands) are used for rendering the actual map canvas and for rendering a temporary canvas for the hit detection. So it is possible to use a different stroke style. We are already using a similar technique for polygon fills. If a polygon is rendered with a transparent fill color, a different fill color is used for the hit detection, so that the polygon can be selected.

I could imagine adding an option `hitDetectionStrokeWidth` to `ol.layer.Vector` and this width will be used by the layer renderer when creating the hit detection replay group.

This would be more efficient than calling `forEachFeatureAtPixel` multiple times.

And as a workaround for now, you could use a second stroke style with an almost transparent stroke color (see https://jsfiddle.net/h4ysLu8q/). But depending on the map background, this style might be visible.

**Comment by giohappy** [comment]
@tsauerwein I like your proposal. Are you going to work on it? Do we want to cooperate with a common funding? @ischas what do you think?
In the meanwhile we're using the same workaround of you with an almost transparent stroke.

**Comment by ischas** [comment]
I talked to my boss. He proposed that @simonseyock can implement it and our company and yours share the costs. What do you think about that? If so we should discuss the funding private (see my email in my profile) and keep this open for technical discussions.

**Comment by bartvde** [comment]
don't forget that a review might need to get paid as well

**Comment by giohappy** [comment]
@icholy I don't know @simonseyock but I trust you. I will tal to my collegues for the funding but we need to have an estimate from him. Shall we go the way suggested by @tsauerwein ?
@bartvde I don't understand what you mean...

**Comment by bartvde** [comment]
what I mean is that if you are going to take into account costs to share, you should budget for a review by a core developer as well. This is needed to get things into the library normally, and cannot be assumed to be done for free all of the time.

**Comment by giohappy** [comment]
ah yes @bartvde I agree. @ahocevar who could review it?

**Comment by ischas** [comment]
@giohappy I guess you mean me when you mentioned the other guy whome you may trust. ;-) Concerning OL3 you should trust @simonseyock more than me since he is far more involved. I'm more or less only the grumbler if something doesn't work.

I acknowledge @bartvde's concern that if the development is funded the whole review process should be funded as well. Maybe he can estimate the costs and elapsed time for the review.

Unfortunately I cannot give any estimation today. Since I'm out of office today and on Monday so I cannot reply before the mid of next week.

Technically I think the proposed way of @tsauerwein sounds feasible but I had no time to evaluate the mentioned method for hit detection of polygons.

**Comment by icholy** [comment]
hey, where did my comments go?

**Comment by icholy** [comment]
Here's what I'm going

```
function pixelDistance(p1: ol.Pixel, p2: ol.Pixel): number {
  let [x1, y1] = p1;
  let [x2, y2] = p2;
  return Math.sqrt(
      Math.pow(x2 - x1, 2) +
      Math.pow(y2 - y1, 2)
  );
}

function getClickedFeature(
  map:       ol.Map,
  source:    ol.Source,
  event:     ol.MapBrowserEvent,
  threshold: number
) {

  let coordinate = event.coordinate,
      feature    = source.getClosestFeatureToCoordinate(coordinate);

  if (!feature) {
    return undefined;
  }

  let geometry = feature.getGeometry(),
      point    = geometry.getClosestPoint(coordinate),
      pixel    = map.getPixelFromCoordinate(point),
      distance = pixelDistance(pixel, event.pixel);

  if (distance > threshold) {
    return undefined;
  }

  return feature;
}
```

**Comment by ahocevar** [comment]
@tsauerwein, would you be willing to review such a pull request and clarify the invoicing with your employer?

I also agree on @tsauerwein's proposal. The name for the new layer option could be simpler, maybe something like `strokeHitTolerance`, which would mean pixels added to any stroke width for the replay canvas, with a default of 0.

**Comment by ischas** [comment]
Should the implementation be limited to strokes or should it be a general solution for vector data? I guess the problem is the same for (poorly styled) points and tiny polygons.

**Comment by giohappy** [comment]
@ischas I suppose it will work anyway, doesn't it? If a temporary stroke will be applied during replay, it should work fine for any geometry. The only limitation I see is that it wouldn't work with image symbols: if a marker is used for points, clicking on the marker won't benefit of the fake stroke. Am I wrong?

**Comment by ischas** [comment]
@giohappy You're totally right. I confused strokes as line geometries with strokes as part of the styling of vector data. Sorry for that.

**Comment by giohappy** [comment]
When the browser event is a TouchEvent, its (single or multiple) touch objects' [radiusX]{https://developer.mozilla.org/en-US/docs/Web/API/Touch/radiusX} and radiusY properties could be considered to define the "strokeHitTolerance", or how it will be called, in case an explicit value wasn't defined

**Comment by ischas** [comment]
@giohappy The handover of the TouchEvent's radius property to the (potentially) new strokeHitTolerance-option of forEachFeatureAtPixel should be in the responsibility of your application.

**Comment by giohappy** [comment]
@ischas right, i agree.

**Comment by giohappy** [comment]
A very useful option in Google Maps styling is the "shape" option. It permits to define the image map used for hit detection. It could also be considered when designing the upgrades to the hit detection options.

@icholy @simonseyock any news about the development proposal and cost estimate?

**Comment by ischas** [comment]
Unfortunately we couldn't make an agreement with Camptocamp ( @tsauerwein ) concerning the review process by now. I don't want to go into the details since this isn't the right place for that.

Either a) the people at Camptocamp change their position, b) your ( @giohappy ) company is willing to sign a service contract with Camptocamp, c) we find another one to review this or d) someone is willing to implement it without yours and ours financial backing to clear the way for a review at no charge.

We won't put any effort into this until the above isn't clarified since a) there is a workaround and b) it's not a high prioritized problem at our company.

**Comment by tsauerwein** [comment]
> Unfortunately we couldn't make an agreement with Camptocamp ( @tsauerwein ) concerning the review process by now. I don't want to go into the details since this isn't the right place for that.

The latest information from my management is, that I can do the review because we are also interested in this feature for our client projects, and given that no considerable guidance is needed during the development. So, the *review question* is cleared. :)

**Comment by ischas** [comment]
@tsauerwein That's great news.

So @simonseyock and me will discuss the implementation soon and will give feedback about our estimated development time. After that @giohappy and we can discuss how to share the costs. Once again, I guess this isn't the right place to discuss this in detail so a mail by you @giohappy to me would be great.

**Comment by tschaub** [comment]
I hope this could be generalized to `hitTolerance`.  Instead of just working with lines, I think it should work for all geometry types.  An alternative to bumping up the stroke on all of the hit detection instructions, the hit context itself could be made larger.  Then, instead of just checking if a single pixel has non-transparent data, we could check if any of the alpha values are non-zero.  This would give you hit detection in a square around the requested pixel.  Refining this, you could check just the alpha values in a circular range of pixels around the center pixel.

Even if the larger stroke method is chosen, I would leave room for this to be extended to all geometry types (and not name the option anything specific to strokes).

**Comment by tsauerwein** [comment]
> As an alternative to bumping up the stroke on all of the hit detection instructions, the hit context itself could be made larger. Then, instead of just checking if a single pixel has non-transparent data, we could check if any of the alpha values are non-zero. This would give you hit detection in a square around the requested pixel. Refining this, you could check just the alpha values in a circular range of pixels around the center pixel.

Good idea! This would also allow to specify the tolerance per `forEachFeatureAtPixel` call (instead of a fixed tolerance per layer).

**Comment by giohappy** [comment]
@tschaub this the [first proposal](https://github.com/openlayers/ol3/issues/5862#issuecomment-245664427). 
The only limitation is that hit detection won't match the symbols. Imagine a point with a marker, I would expect I could simply click (touch) the marker instead of having to click exactly (around) the geometry coordinates. I think this is a common UX.
As I said above, Google Maps offer a "shape" option to define the image map used for hit detection. Maybe this could be also considered, along the simpler tolerance option.

**Comment by ahocevar** [comment]
I think that's a different idea. Currently the hit canvas is 1x1 pixels, and @tschaub suggests to use a bigger hit canvas if I'm not mistaken. I don't understand though how this would work without modifying the hit canvas styles.

**Comment by ahocevar** [comment]
Ah I see now: use a bigger hit canvas, and check if there are any non-transparent pixels in it.

**Comment by giohappy** [comment]
yes @ahocevar.

**Comment by simonseyock** [comment]
@giohappy: the checking with the larger hit canvas should recognize icons, too.

**Comment by giohappy** [comment]
@simonseyock don't the reaplygroups' forEachFeatureAtCoordinate create the 1x1 hit canvas around the geometry's coordinates? How does it consider symbols?

**Comment by ahocevar** [comment]
This method will work with icons too, because it renders the icons. The size of the hit canvas is arbitrary. It is just like a very small map.

**Comment by simonseyock** [comment]
If i understood it correctly a 1x1 canvas is rendered at the point given to the forEachFeatureAtPixel method and after the drawing of each(?) feature it is then checked if the canvas got filled or not.

**Comment by simonseyock** [comment]
maybe it is useful to use a mask (with a custom shape or the shape of a circle) to identify which pixels of an bigger hitCanvas should be checked or not.
This mask could be calculated out of a hit detection radius at the beginning of the forEachFeatureAtCoordinate in the replaygroup. It would be a circle then.

**Comment by giohappy** [comment]
Ah yes @ahocevar, it was my first thought and but after all these posts my
mind was exploding :)

The idea of a "mask shape" as an additional option to numeric tolerance
could fit sone corner situations, but I would start with the tolerance
option and then we'll see.

**Comment by simonseyock** [comment]
I agree I don't see why it would be useful to use something different than a circle.
But this is nevertheless an option to internally reduce the amount of calculations. But this is probably to specific at this point of time.

**Comment by ischas** [comment]
In such situations you could use a diamond as a good approximation to a circle without much calculation cost.

**Comment by simonseyock** [comment]
We were discussing a little about using a bigger hit context in the forEachFeatureAtCoordinate method. We assumed we would provide a hitTolerance as an optional parameter. These are the variants we came up with and some thoughts about them:

**a)** just use a square and call the callback for every feature within. This is easy to implement and fast to compute. This has the drawback that it will return (of course) features outside of the radius. It also can not offer information about the distance of the feature to the given coordinate.

**b)** calculate the distance of the nearest painted pixel to the given coordinate. For this we would have to find out which is the nearest pixel, which would result in quite much computational effort if we would do that for every feature, but we could just precalculate the circle (and the distances if desired) at the beginning of the forEachFeatureAtCoordinate method.
This could be done with either an array of pixel coordinates or a 2-dimensional array in the size of the canvas filled with 1s and 0s indicating if the pixel should be checked or not. This would have a constant computational effort (assuming given the same radius every time) of (2 * radius)^2 distance calculations or if using the symmetry radius^2 calculations.
**optional**: This array could maybe stored and given to the forEachFeatureAtCoordinate instead of a radius.
**optional**: With this method we could provide an information about the distance of the feature to the given coordinate. If would want to do this, we could just sort the array with pixel coordinates by distance to the center and easily find the nearest pixel.

**Comment by simonseyock** [comment]
I think the approach of adding an hitTolerance parameter to the forEachFeatureAtCoordinate method is the most general and therefore the preferable approach to solve this problem.

**Comment by giohappy** [comment]
@simonseyock I like the oportunities given by **b)**, for optimal results, but I would prefer to have the highest possible performances for a hit detection test. I'm inclined to have some false negatives then false positives, which could be achieved using a diamond shape rather then a square. Maybe this could be an additional, optional, parameter...

**Comment by simonseyock** [comment]
ah, of course, instead of a square we could use a diamond, too. This does not make a big difference. What makes a difference is if we try to approach the circle with either the square or the diamond from the outside or the inside. If coming from the outside, a square is easier and if coming from the inside, a diamond is easier.

**Comment by simonseyock** [comment]
If we would prefer false negatives of course a diamond approaching the circle from the inside should be chosen.

**Comment by simonseyock** [comment]
Though this results in some unused pixels to be painted.

**Comment by simonseyock** [comment]
... which probably costs more than calculating a fitting square (?). Sorry for writing so many comments ;)

**Comment by ischas** [comment]
I think this is a redundant discussion. If we determine a square as detection area then the diamond would give the same result quality as a hitDetection-parameter reduced by the factor `sqrt(2)`.

The only relevant question is: Do we accept a square as circle approximation or do we want an exact result?

**Comment by giohappy** [comment]
> I think this is a redundant discussion. If we determine a square as detection area then the diamond would give the same result quality as a hitDetection-parameter reduced by the factor sqrt(2).

Right @ischas, I meant hexagon not diamond. 

> The only relevant question is: Do we accept a square as circle approximation or do we want an exact result?

That's the point, having a shape resembling a circular hit shape but without the computational cost of a true circle.

**Comment by simonseyock** [comment]
Just for mentioning: We could also use [Bresenhams midpoint circle algorithm](https://en.wikipedia.org/wiki/Midpoint_circle_algorithm).

**Comment by simonseyock** [comment]
I noticed the wikipedia article is not so insightful.
The midpoint cirlce algorithm allows to calculate the points of a circle with only integer addition and can be optimized using symmetry. It calculates a circle in sin(PI/4) * r ~ 0.7 * r steps.
The wikipedia article features a example implementation in javascript at the bottom.

**Comment by simonseyock** [comment]
This gives three options to calculate the hit area. Please notice that this calculation has to be done once at the start of forEachFeatureAtCoordinate if we do not save the calculation somehow.
**a)** use square/diamond. Single calculation.
**b)** midpoint circle algorithm. Linear amount of calculations (relative to radius).
**c)** distance to every pixel. Quadratic amount of calculations (relative to radius). This would allow to provide distance to callback.
I think it does not make that much of a difference for (single) touch events with a small radius. It might be a problem for many consecutive calls, i.e. for dragmove.
We should maybe come to a decision somewhen. What do you think @giohappy? And we might need an opinion of the core developers :)

**Comment by tschaub** [comment]
We want to have the option to change the underlying implementation.  So don't provide the distance to the `forEach...` callback.

The `map.forEachFeatureAtPixel()` signature is already pretty awful.  It would be nice to avoid adding an additional optional argument.  An alternative would be to support `hitTolerance` as a layer option.  Or this function could be reworked so it accepts an optional `options` second argument.
E.g. `map.forEachFeatureAtPixel(pixel[, options], callback)`.

**Comment by simonseyock** [comment]
If we don't want to provide the distance to the callback we can rule out option c as it doesn't give any advantage over option b, but costs more.

I would prefer the `hitTolerance` as an argument to `forEachFeatureAtPixel` instead of having it as an layer option. This would give more flexibility, for example for responsive designs which would want to use different radii (less precise for mobile, more precise for desktop) or if you would want to use the touch radius for the `hitTolerance`. And i think it would be more intuitive to set the `hitTolerance` at a point where i am actually handling the event instead of providing at another seemingly unrelated location.

Yes, the signature is quite packed. An options object seems to be a good solution @tschaub. Maybe to keep it easier and not break that much of code, we could provide the options as the last argument:
`map.forEachFeatureAtPixel(pixel, callback[, options])`

**Comment by ischas** [comment]
@giohappy You got quiet! What's your thinking? What is your time schedule concerning this issue? As [mentioned before](https://github.com/openlayers/ol3/issues/5862#issuecomment-247317922) it's not really high on our list by now.

Since Bresenham's algorithm mentioned by @simonseyock computes a circle in linear computation time I would prefer it instead of using less precise geometric approximations of a circle like diamonds, hexagons or similar.

As @tschaub suggested the callback shall not be changed. This means an unsorted list of all features in hit range will be returned.

Are these specifications now final?

**Comment by giohappy** [comment]
@ischas honestly I was a bit confused about the implementation procedure: who will do it? @tsauerwein (camptocamp)? Will it need supplementary acceptance by the core devs?
If it's ok to proceed and all the procedural requirements are met, I would ask @tsauerwein a cost (and schedule) estimate to evaluate if there is enough funding and it meets our timing.

**Comment by ischas** [comment]
@giohappy We have several interested parties in this issue and there are at least three parties who are willing to contribute: camptocamp, your company and ours (Klaus Benndorf). At this time I expected following procedure: @simonseyock will make an cost estimation and schedule and if approved he will implement it. Yours and our company will share the implementation cost. @tsauerwein will do the review (at cost of camptocamp).

**Comment by marcjansen** [comment]
Additional note: @tsauerwein is a core dev.

**Comment by giohappy** [comment]
ok @ischas let's proceed with the estimate.

**Comment by simonseyock** [comment]
I see the following tasks to do:
* Writing a test
* Changing the signature of `map.forEachFeatureAtCoordinate` and `map.forEachFeatureAtPixel` in the source code, the examples and the tests
* Make `ol.render.canvas.ReplayGroup.prototype.forEachFeatureAtCoordinate` work with a hitContext of variable size
* Implementing the midpoint circle algorithm and checking only pixels inside the circle
* Update documentation
* Optionally adding a new example

What we did not talk about before is the webGL renderer. I don't know much about webGL, but the code in `ol.render.webgl.ReplayGroup.prototype.forEachFeatureAtCoordinate` does not look that different to the code in the canvas renderer. 
I would say that we first implement it only for canvas and then think about webGL.

Do you see additional tasks?

**Comment by giohappy** [comment]
I think that's all @simonseyock.

Il 27 set 2016 11:51, "Simon Seyock" <notifications@github.com> ha scritto:

**Comment by simonseyock** [comment]
I estimate roughly a work load of about 8 hours.

Test: 0:30 h
Signature change: 1:30 h
Internal parameter change: 1:00 h
hitContext of variable size: 1:00 h
midpoint circle algorithm: 1:30 h
documentation: 1:30 h
time buffer: 1:00 h

If an example is wished it would take me about an hour.

**Comment by giohappy** [comment]
Ok, great. Cost estimate?

2016-09-28 12:39 GMT+01:00 Simon Seyock <notifications@github.com>:

**Comment by ischas** [comment]
@giohappy Since neither @simonseyock nor I are involved into accounting I may refer you to my colleague Beate Spieckermann ( info@benndorf.de ).

**Comment by giohappy** [comment]
@ischas any news? I wrote to the reported email address....

**Comment by ischas** [comment]
Today is holiday in Germany. Will report tomorrow.

**Comment by ischas** [comment]
Fixed with 5995.

**Comment by EnemyArea** [comment]
Hey ppl, its still broken! Works well in browser, but not on android 4, 6 or later

**Comment by fredj** [comment]
See #6778 and #6834
