### ISSUE TITLE
Vibrating map on zoom, v3.19.0

### ISSUE THREAD

**Issue by michaelletzgus** [openlayers/ol3#6015]
With v3.19.0 the map vibrates when zooming in and out quickly (mouse wheel) on high zoom levels.
Tested with Firefox and Chromium, no problems with v1.18.n.

**Comment by marcjansen** [comment]
Can you create a jsfiddle? And what do you mean by vibrating?

**Comment by michaelletzgus** [comment]
Just try this:
http://openlayers.org/en/latest/examples/simple.html
Zoom as near as possible into a large city, then zoom out a little bit, then zoom in and out quickly using the mouse wheel.

Vibrating means: Randomized Jump (amplitude up to 10x mouse pointers size ) of maps center point while zooming quickly. The effect seems to bee more intense far away from mouse position. The distortion seems to be radial... .

Maybe zoomed and loaded tiles are not matching correctly?

**Comment by bjornharrtell** [comment]
I can reproduce this, it can be quite subtle at times and more pronounced other times haven't found a clear pattern. I've managed to bisect it down to f23921367b8fa8c56cf7f58bc5ebf77517ae7886, @ahocevar any ideas?

**Comment by ahocevar** [comment]
@bjornharrtell What's going on is that the origin we use for aligning tiles can be far off the visible map. This is the case when we render tiles with very different resolutions. The origin will be a corner of the lowest resolution tile, and rounding tile sizes to integers can cause a difference of a few pixels in the center of the map.

I need to think about a way how we could improve this.

**Comment by ahocevar** [comment]
@bjornharrtell Do you think you can help me test? I cannot reproduce this issue very well, but b383c93 should fix it in my opinion. Can you verify please?

**Comment by bjornharrtell** [comment]
Sorry, issue still persists with applied patch and can't see any behavioral change.

**Comment by ahocevar** [comment]
I think we're going to revert #5890. It seems to me the tiny gaps between lower resolution tiles are less disturbing than these offset errors.
